apiVersion: v1
kind: Service
metadata:
  name: nginx-cache
  labels:
    app: nginx-cache
spec:
  selector:
    app: nginx-cache
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  type: ClusterIP
