apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AlexanKoh/Practice_For_DevOps.git
    targetRevision: master
    path: App-of-Apps/simple-manifests/postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: simple-postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
