name: Build and Push Docker Images to GHCR

on:
  #push:
  #branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lowercase image prefix
        run: echo "IMAGE_PREFIX_LC=${IMAGE_PREFIX,,}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build php-fpm image
        run: |
          docker build \
            -f Docker/Dockerfile \
            -t $REGISTRY/$IMAGE_PREFIX_LC/php-fpm:latest \
            Docker

      - name: Push php-fpm image to GHCR
        run: |
          docker push $REGISTRY/$IMAGE_PREFIX_LC/php-fpm:latest

      - name: Build nginx image
        run: |
          docker build \
            -t $REGISTRY/$IMAGE_PREFIX_LC/nginx-custom:latest \
            -f Docker/nginx.Dockerfile Docker

      - name: Push nginx image to GHCR
        run: |
          docker push $REGISTRY/$IMAGE_PREFIX_LC/nginx-custom:latest

      - name: Build website image
        run: |
          docker build \
            -t $REGISTRY/$IMAGE_PREFIX_LC/website:latest \
            -f Docker/website.Dockerfile Docker

      - name: Push website image to GHCR
        run: |
          docker push $REGISTRY/$IMAGE_PREFIX_LC/website:latest
